/**
 * Self-hosts the two Google Fonts.
 *
 * Why: loading them from fonts.googleapis.com sends every visitor's IP to Google
 * before they have consented to anything. On a psychologist's site the mere fact
 * of the visit is sensitive. Self-hosting also removes two cross-origin handshakes
 * from the critical path.
 *
 * Re-run only if the font families change: node scripts/fonts.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const URL_ =
  'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=DM+Sans:opsz,wght@9..40,300..700&display=swap';

mkdirSync('public/assets/fonts', { recursive: true });
const css = await (await fetch(URL_, { headers: { 'User-Agent': UA } })).text();

// Spanish needs latin + latin-ext only. Dropping cyrillic/greek/vietnamese saves
// ~6 files the site would never paint a glyph from.
const blocks = css.split('@font-face').slice(1);
const out = [];

for (const b of blocks) {
  const range = b.match(/unicode-range:\s*([^;]+);/)?.[1] ?? '';
  const isLatin = /U\+0000-00FF/.test(range) || /U\+0100-02(BA|AF)/.test(range);
  if (!isLatin) continue;

  const url = b.match(/url\((https:[^)]+\.woff2)\)/)[1];
  const family = b.match(/font-family:\s*'([^']+)'/)[1];
  const style = b.match(/font-style:\s*([^;]+);/)[1].trim();
  const weight = b.match(/font-weight:\s*([^;]+);/)[1].trim();
  const isExt = !/U\+0000-00FF/.test(range);

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${style}${isExt ? '-ext' : ''}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(`public/assets/fonts/${file}`, buf);

  out.push(
    `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/assets/fonts/${file}') format('woff2');\n` +
      `  unicode-range: ${range};\n}`
  );
  console.log(file, (buf.length / 1024).toFixed(1) + 'KB');
}

writeFileSync(
  'src/styles/fonts.css',
  `/* Generated by scripts/fonts.mjs — do not edit by hand. */\n\n${out.join('\n\n')}\n`
);
console.log(`\n${out.length} faces → src/styles/fonts.css`);
